version: '3'
services:
    # Criação do banco de dados
    db_dixdigital:
        image: mysql:latest
        restart: always
        container_name: dbdixdigital
        ports:
            - "3311:3306"
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dixdigital_db
            MYSQL_USER: dixdigital
            MYSQL_PASSWORD: dixdigital

volumes:
    db_data:
